### ISSUE TITLE
Стандарты редактирования / регистрации формы

### ISSUE THREAD

**Issue by alex-w-dev** [alexander-w-dev/balagan.2.0.ru#10]
- [x]  при редактировании пользователя некоторые поля  (регион проживания, дата рождения) ответ сервера success:false  при этом нет ошибок
http://prntscr.com/fxxkex

- [x] заменить district_code на district_name в user_info , или наоборот в регистрации/редактировании district_name на district_code

- [x] определить стандарт полей (birthDay, birthMonth, dirthYear) для формы регистрации (как с district)  - что мне посылать цифры только  или месяц текстом (1.1.1900, 01.01.1900. 01.Январь.1900  и тд) - дай строгий стандарт для регистрации и редактирования пользователя (сейчас он не сохраняется при регистрации - я не верно посылаю - скажи как надо)

**Comment by ArseniyDyupin** [comment]
месяц отправляй цифрой от 1 до 12

**Comment by alex-w-dev** [comment]
не могу проверить .... #14
