### ISSUE TITLE
Правки после проверки

### ISSUE THREAD

**Issue by Wbmedved** [alexander-w-dev/balagan.2.0.ru#11]
- [x] Не могу зарегистрироваться. Возможно потому что моя почта уже используется. Если это так, то надо выдавать соответствующее сообщение.

- [x] Поиск по клиентам должен быть в строке поиска по клиентам) а где вводишь ид, там должно быть только ид, хотя давай оставим как есть, но тогда нижнюю строку вообще уберём, а у верхней напишем placeholder "введите ИД или ФИО"

- [x] Выводи окошко "ваш запрос успешно отправлен" после отправки запроса

- [x] Миниатюра фотографии не изменяется, надо чтобы она строилась в соответствие с аватаркой

- [x] Добавляем  текст в кабинете врача в раздел сотрудничества с биогеном:
Зарабатывайте вместе с Biogenom без отрыва от основного места работы.

На данный момент для Вас доступно сотрудничество по двум направлениям:

1)      Оказание медицинской услуги в рамках медицинской платформы BIOGENOM;

2)      Прием пациентов по своему профилю через наш сервис «Запись к врачу».

Более подробную информацию Вы можете узнать, позвонив по номеру 8-800-555-96-24

**Comment by alex-w-dev** [comment]
@Wbmedved первый пункт создал задачу  @ArseniyDyupin #13 
2 - фронт готов для бакенда создал задачу @ArseniyDyupin #15
3 - готово
4 - думаю ты говоришь о первоначальной аватарке доктора - изменил, если ты загрузишь новые фотки да и вообще сейчас все ок должно быть
5 сделал
