### ISSUE TITLE
Сделать валидацию полей с пояснениями ошибок

### ISSUE THREAD

**Issue by Wbmedved** [alexander-w-dev/balagan.2.0.ru#12]
Username cannot be blank. плохой ответ))Давайте русскоязычно везде будем проверять и писать по существу.

**Comment by alex-w-dev** [comment]
@ArseniyDyupin 
![image](https://user-images.githubusercontent.com/9738033/28472270-5f603adc-6e59-11e7-8e82-797d4aa42aed.png)
