### ISSUE TITLE
Добавить получение списков с сайта

### ISSUE THREAD

**Issue by alex-w-dev** [alexander-w-dev/balagan.2.0.ru#2]
- [x] все доктора (данные в общепринятом формате (result:[user_info, doctor_info ...])) (на время разработки)

- [x] все пациенты (данные в общепринятом формате (result:[user_info, patient_info ...])) (на время разработки)

- [x] districts (навсегда)

**Comment by ArseniyDyupin** [comment]
сделано

**Comment by ArseniyDyupin** [comment]
settings/all-doctors
settings/all-pacients
settings/districts
