### ISSUE TITLE
Правка уведомлений

### ISSUE THREAD

**Issue by Wbmedved** [alexander-w-dev/balagan.2.0.ru#20]
1)Врачу не должны приходить вот такие уведомления http://storage3.static.itmages.com/i/17/0724/h_1500892109_8429126_af740d7570.png
Ему должны приходить уведомления, когда пользователь одобрил или отказал в доступах.
2)Можно ли чтобы уведомления обновлялись без обновления страницы например раз в минуту?

**Comment by alex-w-dev** [comment]
@Wbmedved  Уведомдения обновляются раз в 10 сек
