### ISSUE TITLE
сервер - создать 3-ий тип пользователя "Партнер"

### ISSUE THREAD

**Issue by alex-w-dev** [alexander-w-dev/balagan.2.0.ru#21]
создать 3-ий тип пользователя "Партнер" (регистрация логин редактирование , фото, уникальных полей пока нет)

**Comment by ArseniyDyupin** [comment]
сделано

**Comment by ArseniyDyupin** [comment]
создается и редактируется обычными функциями в type надо отправлять partner

**Comment by ArseniyDyupin** [comment]
доп полей у него пока нету
