### ISSUE TITLE
выдавать список категорий вопросов (ДЛЯ ЛАБОРАТОРИИ (ПАРТНЕРА))

### ISSUE THREAD

**Issue by alex-w-dev** [alexander-w-dev/balagan.2.0.ru#22]
у вопросов есть парент_ИД (вопросы и категории вопросв в одной таблице (не я придумывал))
для лабратории нас интересует ветка у которой парент_ИД исходит из 800 (поймешь)

вопросы в таблице bio_measure у таблицы есть описание - более подробно спрашивай у Клабукова (контакты давал)

**Comment by ArseniyDyupin** [comment]
сделано

**Comment by ArseniyDyupin** [comment]
параметры mixed и id_parent то есть запилишь 800 и он вернет вопросы для партнера

**Comment by ArseniyDyupin** [comment]
account/anketa
