### ISSUE TITLE
выдавать список вопросов

### ISSUE THREAD

**Issue by alex-w-dev** [alexander-w-dev/balagan.2.0.ru#23]
например тут lk.biogenom.ru/account/anketa?id_parent=821 
контроллеры уже написаны - нужно перенести на АПИ

Вопросы кстати будут дублироваться и для пациента в раздел АНКЕТА апи универсальное (то же самое касаеттся #22 )

**Comment by ArseniyDyupin** [comment]
сделано

**Comment by ArseniyDyupin** [comment]
account/anketa

**Comment by ArseniyDyupin** [comment]
пока есть проверка только по токену, если нужны еще какие то, то пиши, запилю

**Comment by ArseniyDyupin** [comment]
параметры mixed и id_parent то есть запилишь 800 и он вернет вопросы для партнера
