### ISSUE TITLE
сохранять вопросы

### ISSUE THREAD

**Issue by alex-w-dev** [alexander-w-dev/balagan.2.0.ru#24]
Уже есть готовое решение - но оно сохраняет каждый отдельно вопрос - это нам пригодится для анкеты пациента - нужно будет перенести .
Для анализов в которых несколько вопросов думаю будет целесообразно просто передавать на сервер не отдельно вопросы а формой массив вопросов аналогично готовому решению

вобщем нужен апи для сохранения вопросов отдельно (перенести готовый)
и для сохранения массивом (например по кнопке "отправить форму" на фронте)

и как ты понял access токен в данном случае только для идентификации партнера, от меня в форму нужно будет добавлять ИД пациента и массив вопросов аналогично единичным вопросам

и ты надеюсь верно понял что анализы заполянются для пациента партенрами у партенров никакой анкеты нет

**Comment by ArseniyDyupin** [comment]
$url = 'account/set-tests-results-for-partners';
$postdata = array(
    'token' => '4b37daa9c5ba3577827280a34919bd16',
    'user_id' => 18,
    'measure_data' =>json_encode(
        [['type_value' => 2,
        'value' => '234',
        'measure_id' => 11290],
        ['type_value' => 2,
            'value' => 'нет',
            'measure_id' => 11289
        ]])    
);

**Comment by ArseniyDyupin** [comment]
формат запроса такой, есть проверка на партнера, есть проверка на id_parent, можно редактировать только с ид 800
