### ISSUE TITLE
 уведомлять клиента о том что его анализ готов (после сохранениея анализа)

### ISSUE THREAD

**Issue by alex-w-dev** [alexander-w-dev/balagan.2.0.ru#25]
тут все понятно - нужен новый тип уведомления который будет отсылаться пациенту после того как партнер заполнит форму анализов для этого пациента

**Comment by ArseniyDyupin** [comment]
после отработки  'account/set-tests-results-for-partners';
Создается уведомление и пациенту и лечащему врачу

**Comment by ArseniyDyupin** [comment]
тип уведомления partner_send_tests_result
