### ISSUE TITLE
Правки

### ISSUE THREAD

**Issue by Wbmedved** [alexander-w-dev/balagan.2.0.ru#9]
1)Сделать редиректы с http на https. Не только у личных кабинетов, но и вообще у всей группы сайтов biogenom.
2)У врача не должно быть анкеты http://storage7.static.itmages.com/i/17/0719/h_1500453147_4751167_98855c9a7f.png
3)Миниатюра должна быть той фотографии, что загружена
4)Давайте добавим кнопку здесь с текстом "запросить" вместо лупы http://storage1.static.itmages.com/i/17/0719/h_1500453262_9844075_d321338d50.png лупу уберём
5)В строке поиска должен работать автокомплит. он должен искать по именам, фамилиями и отчествам.
6)Запрос на предоставление доступа не должен приходить самому же врачу
7)Вместо слова "Пациент" надо подтягивать ФИО

**Comment by alex-w-dev** [comment]
@Wbmedved `Вместо слова "Пациент" надо подтягивать ФИО`  ну сразу скажу что "Пациент" и есть ФИО ... вообще в макете не логично и не правильно  .... 
первое! надо разделить ФИО на 3 разных инпута - от этого куча проблем и никто так не далет как мы!
второе - логин нужно сделать не по ФИО а по email!  - это тоже хорошая распространенная практика. 
Все что я написал упростит жизнь всем

**Comment by Wbmedved** [comment]
согласен со всем что ты написал)

**Comment by alex-w-dev** [comment]
@ArseniyDyupin  с тебя на бакенде следующий функционал:

- [x] для начала сделай логин по email 

- [x] далее нужно разделить username на 3 поля которые значат фамилию, имя и отчество

- [x] **5)В строке поиска должен работать автокомплит. он должен искать по именам, фамилиями и отчествам.**  - тут нужен соответствующий удаленный метод (и давай сделаем так: ищи не только по фамилии и имени но и по ИД - тоесть если я начну вводить цыфры ты соттветственно будешь искать еще по ID )  в результате давай мне массив объектов (фамилия. имя. отчество. ID). пока ничем не лимитировано бери всё с БД согласно ввобдимым параметрам

- [x]  **6)Запрос на предоставление доступа не должен приходить самому же врачу** к тебе. Если всетаки уведомление хочешь оставить то либо поменяй его тип (название) либо добавь поле говорящее кто инициатор - чтобы я закрыл кнопки "подтвердить" и "отказать".Еще (если ты этого не сделал) поставь защиту, чтобы доктор не мог сам за пациента подтвердить обращение

**Comment by alex-w-dev** [comment]
@ArseniyDyupin 

- [ ] **1)Сделать редиректы с http на https. Не только у личных кабинетов, но и вообще у всей группы сайтов biogenom.** - тоже тебя прошу сделать

**Comment by ArseniyDyupin** [comment]
[18:55:06] Арсений: короче, все сделал, залил, на локалке погонял все робило, базу поправил теперь есть ФИО, юзернейм выпилил, логин идет сейчас по емайлу, емайл сделал уникальным, у юзеров пришлось емайлы пофиксить ну увидишь
[18:55:17] Арсений: FindUsersByFio
[18:55:38] Арсений: требует токена и параметра find
[18:55:47] Арсений: в файнд пихаешь строку
[18:55:51] Арсений: очередность
[18:55:57] Арсений: фамилия имя отчество

**Comment by alex-w-dev** [comment]
@ArseniyDyupin **6 пункт** - врачу уведомление не нужно! (я сделал алерт - можно убрать)
![image](https://user-images.githubusercontent.com/9738033/28472706-08652ae2-6e5b-11e7-8b18-2a3cead3727d.png)


**1 пункт:**
HTTP -> HTTPS редирект в силе (сайты biogenom.ru, lk.biogenom.ru, lk2.biogenom.ru)
